/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    readonly "/api/v1/daily-reports": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /** Create Daily Report */
        readonly post: operations["create_daily_report_api_v1_daily_reports_post"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/daily-reports/{report_id}": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        /** Update Daily Report */
        readonly put: operations["update_daily_report_api_v1_daily_reports__report_id__put"];
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/daily-reports/history": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** List Daily History */
        readonly get: operations["list_daily_history_api_v1_daily_reports_history_get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/daily-reports/me": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** List My Daily Reports */
        readonly get: operations["list_my_daily_reports_api_v1_daily_reports_me_get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/daily-reports/options": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Get Daily Options */
        readonly get: operations["get_daily_options_api_v1_daily_reports_options_get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/me": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Get Me */
        readonly get: operations["get_me_api_v1_me_get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/teams": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** List Teams */
        readonly get: operations["list_teams_api_v1_teams_get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/teams/{team_id}/overview": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Get Team Overview */
        readonly get: operations["get_team_overview_api_v1_teams__team_id__overview_get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/teams/{team_id}/templates/active": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Get Active Template */
        readonly get: operations["get_active_template_api_v1_teams__team_id__templates_active_get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/weekly-reports/{report_id}": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Get Weekly Report */
        readonly get: operations["get_weekly_report_api_v1_weekly_reports__report_id__get"];
        /** Update Weekly Report */
        readonly put: operations["update_weekly_report_api_v1_weekly_reports__report_id__put"];
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/weekly-reports/{report_id}/confirm": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /** Confirm Weekly Report */
        readonly post: operations["confirm_weekly_report_api_v1_weekly_reports__report_id__confirm_post"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/weekly-reports/{report_id}/publish": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /** Publish Weekly Report */
        readonly post: operations["publish_weekly_report_api_v1_weekly_reports__report_id__publish_post"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/weekly-reports/{report_id}/revisions": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /** Create Weekly Revision */
        readonly post: operations["create_weekly_revision_api_v1_weekly_reports__report_id__revisions_post"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/weekly-reports/generate": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /** Generate Weekly Report */
        readonly post: operations["generate_weekly_report_api_v1_weekly_reports_generate_post"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/health/live": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Liveness */
        readonly get: operations["liveness_health_live_get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/health/ready": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Readiness */
        readonly get: operations["readiness_health_ready_get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/version": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Version */
        readonly get: operations["version_version_get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActiveBlocker */
        readonly ActiveBlocker: {
            /** Agedays */
            readonly ageDays: number;
            /**
             * Blockedsince
             * Format: date
             */
            readonly blockedSince: string;
            /** Effectiveblocker */
            readonly effectiveBlocker: string;
            /** Nextaction */
            readonly nextAction: string;
            /** Projectid */
            readonly projectId: string;
            /** Reportid */
            readonly reportId: string;
            /** Userid */
            readonly userId: string;
            /** Workitemid */
            readonly workItemId: string;
        };
        /** Coverage */
        readonly Coverage: {
            /** Expected */
            readonly expected: number;
            /** Percentage */
            readonly percentage: number;
            /** Submitted */
            readonly submitted: number;
        };
        /** DailyReportCreate */
        readonly DailyReportCreate: {
            /** Blocker */
            readonly blocker?: string | null;
            /** Nextaction */
            readonly nextAction: string;
            /** Projectid */
            readonly projectId: string;
            /** Reportdate */
            readonly reportDate?: string | null;
            readonly status: components["schemas"]["WorkStatus"];
            /** Teamid */
            readonly teamId: string;
            /** Workitemid */
            readonly workItemId: string;
            /** Worksummary */
            readonly workSummary: string;
        };
        /** DailyReportRead */
        readonly DailyReportRead: {
            /** Blocker */
            readonly blocker: string | null;
            /**
             * Createdat
             * Format: date-time
             */
            readonly createdAt: string;
            /** Effectiveblocker */
            readonly effectiveBlocker: string | null;
            /** Id */
            readonly id: string;
            /** Lasteditedat */
            readonly lastEditedAt: string | null;
            /** Nextaction */
            readonly nextAction: string;
            /** Projectid */
            readonly projectId: string;
            /**
             * Reportdate
             * Format: date
             */
            readonly reportDate: string;
            /** Source */
            readonly source: string;
            readonly status: components["schemas"]["WorkStatus"];
            /**
             * Submittedat
             * Format: date-time
             */
            readonly submittedAt: string;
            /** Teamid */
            readonly teamId: string;
            /**
             * Updatedat
             * Format: date-time
             */
            readonly updatedAt: string;
            /** Userid */
            readonly userId: string;
            /** Workitemid */
            readonly workItemId: string;
            /** Worksummary */
            readonly workSummary: string;
        };
        /** DailyReportUpdate */
        readonly DailyReportUpdate: {
            /** Blocker */
            readonly blocker?: string | null;
            /** Nextaction */
            readonly nextAction?: string | null;
            readonly status?: components["schemas"]["WorkStatus"] | null;
            /** Worksummary */
            readonly workSummary?: string | null;
        };
        /** HTTPValidationError */
        readonly HTTPValidationError: {
            /** Detail */
            readonly detail?: readonly components["schemas"]["ValidationError"][];
        };
        /**
         * Permission
         * @enum {string}
         */
        readonly Permission: "SUBMIT_OWN_DAILY" | "VIEW_OWN_HISTORY" | "GENERATE_OWN_WEEKLY" | "VIEW_TEAM_DAILY_SUMMARY" | "GENERATE_TEAM_WEEKLY" | "GENERATE_MULTI_TEAM_WEEKLY" | "MANAGE_TEAMS_BINDING";
        /** PublicationRead */
        readonly PublicationRead: {
            /** Actorid */
            readonly actorId: string;
            /** Conversationid */
            readonly conversationId: string;
            /** Id */
            readonly id: string;
            /** Idempotencykey */
            readonly idempotencyKey: string;
            /**
             * Publishedat
             * Format: date-time
             */
            readonly publishedAt: string;
            /** Weeklyreportid */
            readonly weeklyReportId: string;
        };
        /** PublicationRequest */
        readonly PublicationRequest: {
            /** Conversationid */
            readonly conversationId: string;
        };
        /** ReporterSummary */
        readonly ReporterSummary: {
            /** Id */
            readonly id: string;
            /** Name */
            readonly name: string;
        };
        /**
         * ReportScope
         * @enum {string}
         */
        readonly ReportScope: "MEMBER" | "TEAM" | "MULTI_TEAM";
        /** SessionSnapshot */
        readonly SessionSnapshot: {
            /** Email */
            readonly email: string;
            /** Id */
            readonly id: string;
            /** Name */
            readonly name: string;
            /** Teams */
            readonly teams: readonly components["schemas"]["TeamAccess"][];
            /** Tenantid */
            readonly tenantId: string;
        };
        /** TeamAccess */
        readonly TeamAccess: {
            /** Permissions */
            readonly permissions: readonly components["schemas"]["Permission"][];
            readonly role: components["schemas"]["TeamRole"];
            /** Teamid */
            readonly teamId: string;
            /** Teamname */
            readonly teamName: string;
            /** Timezone */
            readonly timezone: string;
        };
        /** TeamOverview */
        readonly TeamOverview: {
            /** Blockers */
            readonly blockers: readonly components["schemas"]["ActiveBlocker"][];
            readonly coverage: components["schemas"]["Coverage"];
            /** Missingreporters */
            readonly missingReporters: readonly components["schemas"]["ReporterSummary"][];
            /**
             * Reportingdate
             * Format: date
             */
            readonly reportingDate: string;
            /** Statuscounts */
            readonly statusCounts: {
                readonly [key: string]: number;
            };
        };
        /**
         * TeamRole
         * @enum {string}
         */
        readonly TeamRole: "MEMBER" | "TECH_LEAD" | "PM";
        /** ValidationError */
        readonly ValidationError: {
            /** Context */
            readonly ctx?: Record<string, never>;
            /** Input */
            readonly input?: unknown;
            /** Location */
            readonly loc: readonly (string | number)[];
            /** Message */
            readonly msg: string;
            /** Error Type */
            readonly type: string;
        };
        /** WeeklyGenerateRequest */
        readonly WeeklyGenerateRequest: {
            readonly scope: components["schemas"]["ReportScope"];
            /** Subjectuserid */
            readonly subjectUserId?: string | null;
            /** Teamid */
            readonly teamId?: string | null;
            /** Teamids */
            readonly teamIds?: readonly string[];
            /**
             * Weekstart
             * Format: date
             */
            readonly weekStart: string;
        };
        /** WeeklyReportRead */
        readonly WeeklyReportRead: {
            /** Confirmedat */
            readonly confirmedAt: string | null;
            /** Contentjson */
            readonly contentJson: {
                readonly [key: string]: unknown;
            };
            /** Generationmetadata */
            readonly generationMetadata: {
                readonly [key: string]: unknown;
            };
            /** Generationsource */
            readonly generationSource: string;
            /** Id */
            readonly id: string;
            /** Inputrecordids */
            readonly inputRecordIds: readonly string[];
            /** Missingcontributors */
            readonly missingContributors: readonly string[];
            readonly scope: components["schemas"]["ReportScope"];
            readonly status: components["schemas"]["WeeklyReportStatus"];
            /** Subjectuserid */
            readonly subjectUserId: string | null;
            /** Supersedesid */
            readonly supersedesId: string | null;
            /** Teamid */
            readonly teamId: string | null;
            /** Teamids */
            readonly teamIds?: readonly string[];
            /** Templateid */
            readonly templateId: string;
            /** Templateversion */
            readonly templateVersion: number;
            /**
             * Weekend
             * Format: date
             */
            readonly weekEnd: string;
            /**
             * Weekstart
             * Format: date
             */
            readonly weekStart: string;
        };
        /**
         * WeeklyReportStatus
         * @enum {string}
         */
        readonly WeeklyReportStatus: "DRAFT" | "GENERATED" | "EDITED" | "CONFIRMED";
        /** WeeklyUpdateRequest */
        readonly WeeklyUpdateRequest: {
            /** Contentjson */
            readonly contentJson: {
                readonly [key: string]: unknown;
            };
        };
        /**
         * WorkStatus
         * @enum {string}
         */
        readonly WorkStatus: "NOT_STARTED" | "IN_PROGRESS" | "BLOCKED" | "READY_FOR_REVIEW" | "DONE";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    readonly create_daily_report_api_v1_daily_reports_post: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": components["schemas"]["DailyReportCreate"];
            };
        };
        readonly responses: {
            /** @description Successful Response */
            readonly 201: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["DailyReportRead"];
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readonly update_daily_report_api_v1_daily_reports__report_id__put: {
        readonly parameters: {
            readonly query: {
                readonly teamId: string;
            };
            readonly header?: never;
            readonly path: {
                readonly report_id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": components["schemas"]["DailyReportUpdate"];
            };
        };
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["DailyReportRead"];
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readonly list_daily_history_api_v1_daily_reports_history_get: {
        readonly parameters: {
            readonly query: {
                readonly dateFrom?: string | null;
                readonly dateTo?: string | null;
                readonly projectId?: string | null;
                readonly status?: components["schemas"]["WorkStatus"] | null;
                readonly teamId: string;
            };
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": readonly components["schemas"]["DailyReportRead"][];
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readonly list_my_daily_reports_api_v1_daily_reports_me_get: {
        readonly parameters: {
            readonly query: {
                readonly teamId: string;
            };
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": readonly components["schemas"]["DailyReportRead"][];
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readonly get_daily_options_api_v1_daily_reports_options_get: {
        readonly parameters: {
            readonly query: {
                readonly teamId: string;
            };
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": {
                        readonly [key: string]: readonly {
                            readonly [key: string]: string;
                        }[];
                    };
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readonly get_me_api_v1_me_get: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["SessionSnapshot"];
                };
            };
        };
    };
    readonly list_teams_api_v1_teams_get: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": readonly components["schemas"]["TeamAccess"][];
                };
            };
        };
    };
    readonly get_team_overview_api_v1_teams__team_id__overview_get: {
        readonly parameters: {
            readonly query?: {
                readonly reportingDate?: string | null;
            };
            readonly header?: never;
            readonly path: {
                readonly team_id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["TeamOverview"];
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readonly get_active_template_api_v1_teams__team_id__templates_active_get: {
        readonly parameters: {
            readonly query: {
                readonly scope: components["schemas"]["ReportScope"];
            };
            readonly header?: never;
            readonly path: {
                readonly team_id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": {
                        readonly [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readonly get_weekly_report_api_v1_weekly_reports__report_id__get: {
        readonly parameters: {
            readonly query?: {
                readonly teamId?: string | null;
            };
            readonly header?: never;
            readonly path: {
                readonly report_id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["WeeklyReportRead"];
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readonly update_weekly_report_api_v1_weekly_reports__report_id__put: {
        readonly parameters: {
            readonly query?: {
                readonly teamId?: string | null;
            };
            readonly header?: {
                readonly "Idempotency-Key"?: string | null;
            };
            readonly path: {
                readonly report_id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": components["schemas"]["WeeklyUpdateRequest"];
            };
        };
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["WeeklyReportRead"];
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readonly confirm_weekly_report_api_v1_weekly_reports__report_id__confirm_post: {
        readonly parameters: {
            readonly query?: {
                readonly teamId?: string | null;
            };
            readonly header?: {
                readonly "Idempotency-Key"?: string | null;
            };
            readonly path: {
                readonly report_id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["WeeklyReportRead"];
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readonly publish_weekly_report_api_v1_weekly_reports__report_id__publish_post: {
        readonly parameters: {
            readonly query?: never;
            readonly header: {
                readonly "Idempotency-Key": string;
            };
            readonly path: {
                readonly report_id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": components["schemas"]["PublicationRequest"];
            };
        };
        readonly responses: {
            /** @description Successful Response */
            readonly 201: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["PublicationRead"];
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readonly create_weekly_revision_api_v1_weekly_reports__report_id__revisions_post: {
        readonly parameters: {
            readonly query?: {
                readonly teamId?: string | null;
            };
            readonly header?: {
                readonly "Idempotency-Key"?: string | null;
            };
            readonly path: {
                readonly report_id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 201: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["WeeklyReportRead"];
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readonly generate_weekly_report_api_v1_weekly_reports_generate_post: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: {
                readonly "Idempotency-Key"?: string | null;
            };
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": components["schemas"]["WeeklyGenerateRequest"];
            };
        };
        readonly responses: {
            /** @description Successful Response */
            readonly 201: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["WeeklyReportRead"];
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readonly liveness_health_live_get: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": {
                        readonly [key: string]: string;
                    };
                };
            };
        };
    };
    readonly readiness_health_ready_get: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": {
                        readonly [key: string]: unknown;
                    };
                };
            };
        };
    };
    readonly version_version_get: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": {
                        readonly [key: string]: string;
                    };
                };
            };
        };
    };
}
